[package]
name = "diecast-github-pages"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
diecast = {path = "../diecast"}
docopt = "*"
rustc-serialize = "*"
git2 = "*"
regex = "*"
url = "*"
